### ISSUE TITLE
stormpath-sdk-angularjs NPM install hangs on Windows 10

### ISSUE THREAD

**Issue by WDShannon** [stormpath/stormpath-sdk-angularjs#174]
I'm not sure if this is my problem or npm or you, but when I try to npm install this repo it just indefinitely hangs.  I am able to install any other npm package without issue.  I am on windows 10.

**Comment by Doug-Shannon** [comment]
have tried on multiple window machines, it is still failing.  There is clearly an issue with the package.  Any way around this, it is time sensitive.

**Comment by mdeggies** [comment]
@WDShannon and @Doug-Shannon, can you both please post what version of node and npm you're on? We're looking into this!

**Comment by Doug-Shannon** [comment]
Hey there, sorry, both above comments were mine, didn't mean to log in with each.  Current npm version is 3.9.5 and node version is 6.2.2.

This is failing on our Visual Studio Team Services build server too.

**Comment by Doug-Shannon** [comment]
![image](https://cloud.githubusercontent.com/assets/19997906/18651673/c0fd8448-7e9a-11e6-8105-fa2e8352b365.png)

this is the NPM output.

**Comment by robertjd** [comment]
Hi @Doug-Shannon , I'ved tried to reproduce this on a Windows 10 virtual machine, but haven't had any luck.  I'm using the same node and npm versions, installed via [nodist](https://github.com/marcelklehr/nodist), and using the windows command line.  The npm install completes as expected for me.  Can you tell me what terminal program you're using?  Could you see if the logging features in npm give any more details about where the hangup is?  Thanks!

**Comment by Doug-Shannon** [comment]
So I'm not sure what nodist is, I've only ever installed with the windows MSI directly from the nodejs site: https://nodejs.org/en/download/, this may be a source of the difference.  The real problem is that this is causing my build server to hang as well and I don't have a solution for it (I can get by locally by downloading the package manually).  As far as terminal, I'm just using command prompt  I included the picture above that shows the output of npm, I'll look to see if I can find some other npm debug info.

**Comment by Doug-Shannon** [comment]
Any updates on this?

**Comment by robertjd** [comment]
Hi Doug, my apologies but I haven't had a chance to try other variations on windows.  Can I bother you to open a ticket by contacting support@stormpath.com?  Please reference our conversation on this issue.  I'd like to have you do a screenshare with someone on our team who is more familiar with windows.  Thanks!

**Comment by mdeggies** [comment]
Hi @Doug-Shannon -- tried to contact you via support@stormpath.com and on slack, but haven't heard a reply yet. Happy to set up a screenshare to figure out what the problem is. Just let me know! -M

**Comment by nbarbettini** [comment]
I've reproduced this on both Windows 8 and Windows 10 with node 6.6.0 and npm 3.10.8 (latest). I think it's a bug in npm, which I posted here: https://github.com/npm/npm/issues/14059

My only other wild guess is a filename that Windows doesn't like for some reason. It hangs on extracting `.tmp/build/stormpath-sdk-angularjs.tpls.min.js` which certainly doesn't seem like a weird path to me.

**Comment by Doug-Shannon** [comment]
The NPM team has not made any movement on this.. Is there a way to package this differently inside so it will work?

**Comment by mraible** [comment]
@Doug-Shannon Can you try Yarn and see if it works? https://www.infoq.com/news/2016/10/yarn

**Comment by Doug-Shannon** [comment]
I've considered yarn, but I am not sure how it will run on our azure build server.  I'll give it a try and see how it goes.

**Comment by Doug-Shannon** [comment]
Yarn is getting stuck on the stormpath package too.

**Comment by Doug-Shannon** [comment]
This has to be something with stormpath, I've had no other packages with this issue.

**Comment by mraible** [comment]
It works fine for me, what versions of Node and npm are you using? Here's mine:

```
$ node --version
v4.5.0
$ npm -version
3.10.6
```

**Comment by Doug-Shannon** [comment]
makes no difference, I have tried all sorts.  I was on node 6.9.1, npm 3.10.6.  Just tried node 4.6.1 with latest npm and it made no difference.  

What I don't get is why stormpath is the only npm library I am struggling with.  There cannot be much going on that many other libraries aren't doing.

**Comment by mraible** [comment]
Can you install it via bower?

```
$ bower install stormpath-sdk-angularjs
bower stormpath-sdk-angularjs#* cached https://github.com/stormpath/stormpath-sdk-angularjs.git#1.1.0
bower stormpath-sdk-angularjs#*         validate 1.1.0 against https://github.com/stormpath/stormpath-sdk-angularjs.git#*
bower angular#>=1.2.*                     cached https://github.com/angular/bower-angular.git#1.5.8
bower angular#>=1.2.*                   validate 1.5.8 against https://github.com/angular/bower-angular.git#>=1.2.*
bower stormpath-sdk-angularjs#^1.1.0     install stormpath-sdk-angularjs#1.1.0
bower angular#>=1.2.*                    install angular#1.5.8

stormpath-sdk-angularjs#1.1.0 bower_components/stormpath-sdk-angularjs
└── angular#1.5.8

angular#1.5.8 bower_components/angular
```

**Comment by mraible** [comment]
FWIW, I do see some warnings when running `bower install` in Travis:

```
bower not-cached    https://github.com/stormpath/stormpath-sdk-angularjs.git#1.0.0
bower resolve       https://github.com/stormpath/stormpath-sdk-angularjs.git#1.0.0
bower checkout      stormpath-sdk-angularjs#1.0.0
bower invalid-meta  The "main" field cannot contain minified files
bower invalid-meta  The "main" field cannot contain minified files
bower invalid-meta  The "main" field has to contain only 1 file per filetype; found multiple .js files: ["dist/stormpath-sdk-angularjs.min.js","dist/stormpath-sdk-angularjs.tpls.min.js"]
bower resolved      https://github.com/stormpath/stormpath-sdk-angularjs.git#1.0.0
bower install       stormpath-sdk-angularjs#1.0.0
```

**Comment by Doug-Shannon** [comment]
It installs with bower, but we aren't using bower on this project.  Any ideas?  I'm not sure what goes into building an npm project, but is there another way to accomplish the step that is failing?

**Comment by mraible** [comment]
What happens when you do this?

```
git clone https://github.com/mraible/21-points.git
cd 21-points
npm install stormpath-sdk-angularjs
```

When I do this, I get:

```
$ npm install stormpath-sdk-angularjs
21-points@2.0.0 /Users/mraible/dev/21-points
└── stormpath-sdk-angularjs@1.1.0
```

**Comment by Doug-Shannon** [comment]
![image](https://cloud.githubusercontent.com/assets/19997906/19616292/0a1aa588-97dd-11e6-822a-ba77ce601d12.png)

same thing.  I get stuck on that `don't care about contents; nuking ....`

**Comment by nbarbettini** [comment]
FWIW @mraible, I was able to reproduce this on Windows but never on Linux or Mac. I don't know what it could be in the package that would cause it.

**Comment by Doug-Shannon** [comment]
What are our next steps.  Npm seems to have labeled the issue we created as a support issue and not a bug, but this is a big pain point for us.

**Comment by mraible** [comment]
@Doug-Shannon I'm able to reproduce this on a Windows 10 VM in Parallels Desktop. That's the good news. I suspect it's caused by long filenames, but according to [this Stack Overflow thread](http://stackoverflow.com/questions/26155135/node-npm-windows-file-paths-are-too-long-to-install-packages), many of these issues were fixed in npm 3. I even tried [upgrading to npm 4](https://github.com/felixrieseberg/npm-windows-upgrade), but that didn't help.

**Comment by mraible** [comment]
I might've figured out a workaround - installing it directly from GitHub seems to work:

```
npm install https://github.com/stormpath/stormpath-sdk-angularjs.git --save
```

This ends up looking like the following in your `package.json`:

```
"stormpath-sdk-angularjs": "git+https://github.com/stormpath/stormpath-sdk-angularjs.git"
```

It seems to point to a particular commit too, but it would be nice if you could point it to a tag.

On a related note, I tried cloning the project (on Windows and Mac) and building the tarball using `npm pack`. I then tried to install it using `npm install stormpath-sdk-angularjs-1.1.0.tgz`. It worked on Windows 10, both from the tarball I built on Mac and the one I built on Windows.

**Comment by Doug-Shannon** [comment]
Is there maybe a corruption in the package hosted on NPM, or is this truly an NPM bug?

Also, the work around should be super helpful, thank you.

**Comment by Doug-Shannon** [comment]
so the work around here is an issue because it forces us to be on the latest version, which is breaking our build.  Also, I tested it out, using NPM the way it was meant to with storm path STILL HANGS, even on 2.0.  

Is there a way to target a specific version?

**Comment by Doug-Shannon** [comment]
adding #1.1.1 to the end of "stormpath-sdk-angularjs": "git+https://github.com/stormpath/stormpath-sdk-angularjs.git" allowed me to target that specific commit.

I would still LOVE for this npm issue to be fixed.

**Comment by robertjd** [comment]
Hi @Doug-Shannon , thanks for the update.  Please continue with that workaround for now, until we can find some time to dig into the cause of the hang.  It might require us to start pulling dependencies one-by-one.
